sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t mortezalatifi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mortezalatifi/docker-react npm run test 
  # Without "-e CI=true" after running the test the command line stays at the test result page.
  # By adding this we get back to the command line after running the tests.